name: setup-avra-cli-action
description: github action to build and install avra cli
branding:
  icon: terminal
  color: white
runs:
  using: composite
  steps:
  - run: ./build.sh
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
    env:
      NEOMURA_SETUP_AVRA_CLI_ACTION_REPOSITORY: ${{ GITHUB.ACTION_REPOSITORY }}
      NEOMURA_SETUP_AVRA_CLI_ACTION_REF: ${{ GITHUB.ACTION_REF }}
